export enum CATEGORIES {
  ALL_BOOKS = 'All Books',
  ADVENTURE = 'Adventure',
  CONTEMPORARY = 'Contemporary',
  ROMANCE = 'Romance',
  FANTASY = 'Fantasy',
  DYSTOPIAN = 'Dystopian',
  MYSTERY = 'Mystery',
  HORROR = 'Horror',
  THRILLER = 'Thriller',
  PARANORMAL = 'Paranormal',
  HISTORICAL_FI = 'Historical Fi',
  SCIFI = 'Scifi',
  MEMOIR = 'Memoir',
  SPORTS = 'Sports',
}
